language: c
dist: trusty
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh

env:
  global:
    - PACKAGE=JS_Parser UBUNTU_TRUSTY=1
  matrix:
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.04

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.opam
